version: "3.9"

services:
  db:
    image: postgres:16
    container_name: barbercloud-postgres-dev
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432" # DEV exposto

    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

    networks:
      - barbercloud_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_DEV} -d ${POSTGRES_DB_DEV}"]
      interval: 10s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbercloud-api-dev
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      POSTGRES_CONNECTION_DEV: ${POSTGRES_CONNECTION_DEV}
      JWT__KEY: ${JWT__KEY}

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_NAME: ${EMAIL_NAME}

      FRONTEND_URL_DEV: ${FRONTEND_URL}
      API_URL_DEV: ${API_URL}

      ASPNETCORE_URLS: http://0.0.0.0:8080

    ports:
      - "8080:8080"

    networks:
      - barbercloud_net


volumes:
  postgres_dev_data:


networks:
  barbercloud_net:
    name: barbercloud-dev_barbercloud_net
    driver: bridge
