version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbearia_api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=POSTGRES_FORTE_AQUI;Database=barbearia_db"
      Jwt__Key: "JWT_FORTE_AQUI"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: barbearia_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_FORTE_AQUI
      POSTGRES_DB: barbearia_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
